# see https://jupyterbook.org/customize/config.html
title: Pywracetrack
author: Avi

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/avivajpeyi/pyracetrack
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
